---
modules-search: [local]

instances:
  - id: sideral
    module: shellprocess
    config: shellprocess-sideral.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - shellprocess@sideral
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - hwclock
      - services-systemd
      - bootloader-config
      - grubcfg
      - bootloader
      - initramfs
      - umount
  - show:
      - finished

branding: sideral
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
