input {
    kb_layout = br
    kb_variant = abnt2
    follow_mouse = 1
    sensitivity = 0

    natural_scroll = true   # mouse wheel inverted

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace
