---
efiSystemPartition:     /boot
efiSystemPartitionSize: 512M
efiSystemPartitionName: SIDERAL_ESP

userSwapChoices:
    - none
    - small
    - hibernation

drawNestedPartitions:   true
alwaysShowPartitionLabels: true

initialPartitioningChoice: erase
initialSwapChoice:         small

defaultFileSystemType:  btrfs

partitionLayout:
    - name: ""
      filesystem: btrfs
      mountPoint: "/"
      size: 100%
      mountOptions:
          - "compress=zstd:1"
          - "ssd"
          - "noatime"
      btrfsSubvolumes:
          - mountPoint: /
            subvolume: "@"
          - mountPoint: /home
            subvolume: "@home"
          - mountPoint: /var
            subvolume: "@var"
          - mountPoint: /var/log
            subvolume: "@log"
          - mountPoint: /.snapshots
            subvolume: "@snapshots"

luksGeneration: luks2
enableLuksAutomatedPartitioning: true
