---
defaultGroups:
    - users
    - wheel
    - networkmanager
    - video
    - audio
    - input
    - render
    - storage

autologinGroup:  autologin
sudoersGroup:    wheel

setRootPassword: false
doReusePassword: true
doAutologin:     false

passwordRequirements:
    minLength:           8
    nonempty:            true
    libpwquality:
        - minlen=8
        - minclass=2

userShell: /run/current-system/sw/bin/zsh
