#!/usr/bin/env bash
# sideral installer pre-install hook — reads lspci to pick the open-source
# vs nvidia variant, copies the flake repo onto the target, and writes the
# target's /etc/nixos/configuration.nix to import the matching host module.
#
# Invoked by calamares between `mount` and `unpackfs`. $1 is the target
# root path (typically /mnt during install).

set -euo pipefail

TARGET_ROOT="${1:-/mnt}"
LOG_PREFIX="[sideral-pre-install]"

log() { printf '%s %s\n' "$LOG_PREFIX" "$*"; }

log "target root: $TARGET_ROOT"

if lspci 2>/dev/null | grep -qiE 'vga.*nvidia|3d.*nvidia|display.*nvidia'; then
    HOST="sideral-nvidia"
    log "detected NVIDIA GPU → host: $HOST"
else
    HOST="sideral"
    log "no NVIDIA GPU detected → host: $HOST"
fi

mkdir -p "$TARGET_ROOT/etc/nixos"

if [ -d /etc/sideral/flake ]; then
    log "copying flake repo into $TARGET_ROOT/etc/nixos/sideral"
    cp -a /etc/sideral/flake "$TARGET_ROOT/etc/nixos/sideral"
else
    log "WARNING: /etc/sideral/flake not present in live env — target will need a manual flake clone"
fi

cat > "$TARGET_ROOT/etc/nixos/configuration.nix" <<EOF
# Auto-generated by sideral installer — references the bundled flake at
# /etc/nixos/sideral. \`sudo nixos-rebuild switch\` will rebuild against it.
#
# To switch variants later: edit the host import path below.
{ ... }: {
  imports = [
    ./sideral/hosts/${HOST}.nix
    ./hardware-configuration.nix
  ];

  system.stateVersion = "25.11";
}
EOF

log "wrote $TARGET_ROOT/etc/nixos/configuration.nix → host=$HOST"
log "done"
